INSERT INTO deck_types (
      id
    , name
    , created_at
    , updated_at
)
VALUES
      (1, 'WITH_CAPTIONS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (2, 'WITHOUT_CAPTIONS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (3, 'METAPHORICAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;
