INSERT INTO magister_cards_descriptions (
      id
    , magister_card_id
    , short_description
    , long_description
    , language
    , created_at
    , updated_at
)
VALUES
      (1,   1, 'Зеўс - галоўны з богаў-алімпійцаў, які кіруе сусветам. Арол - любімая птушка Зеўса, яго памагаты. Мнемазіна, спакушаная Зеўсам, - багіня, якая ўвасабляе памяць і веды, натхняе творцаў.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (2,   2, 'Дыяніс, ён жа Бахус, ён жа Вакх - бог сонечнага цяпла, жывой сілы прыроды, а таксама - бог віна і яго ўзбуджальнага дзеяння на чалавека.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (3,   3, 'Багіня кахання, нараджэння, вечнай вясны. Нарадзілася ў моры з кропляў крыві і семені Ўрана.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (4,   4, 'Эпізод пераўтварэння Дафны ў лаўровае дрэўца, як адзіны шлях пазбегнуць любоўнага пераследу Апалона.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (5,   5, 'Багіня ўрадлівасці і царства мёртвых, уладычыца пекла. 7 зерняў гранату ад каварнага мужа назаўсёды зачынілі яе ў царстве Аіда.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (6,   6, 'Афіна таемна гадавала Эрыхтонія, даўшы яму пры нараджэнні 2 кроплі (жыцця і смерці) крыві Гаргоны.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (7,   7, 'Амфітрыта - адна з нерэідаў, дачка марскога бога Нерэя і жонка Пасейдона. Амфітрыта шанавалася нароўні з мужам, Гамэр згадвае яе, як багіню, якой падуладныя марскія пачвары.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (8,   8, 'Гея - маці продкаў і, агулам, усяго жыцця. Яна была маці Ўрана (неба), ад саюзу з якім з''явіліся, у тым ліку, цыклопы.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (9,   9, 'Лімнада, Нерэіда і Наяда - водныя німфы. У іншых стыхіяў былі свае німфы, але водныя лічыліся найбольш уплывовымі.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (10,  10, 'Дрыяды - лясныя німфы, апякункі дрэваў. З тых нешматлікіх німфаў, што смяротныя. Лічылася, што дрыяды неаддзельныя ад дрэва, з якім звязана, і памірае, калі памрэ дрэва.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (11,  11, 'Зеўс у выглядзе белага быка, з''явіўся на пляжы, дзе Еўропа бавіла час з сяброўкамі. Скраў прыгажуню і звёз на Крыт.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (12,  12, 'Эпізод нараджэння Алены - будучай жонкі Менелая, ад Леды і Зеўса ў абліччы лебедзя.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (13,  13, 'Сірэны ўвасаблялі чароўную, але каварную марскую паверхню, пад якой хаваюцца вострыя скалы і водмелі.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (14,  14, 'Гуго дэ Пэйн - заснавальнік Ордэна Тампліераў і яго першы Вялікі Магістр. Таксама ён стварыў кодэкс паводзінаў чальцоў Ордэна.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (15,  15, 'Вялікі Магістр Ордэна Тампліераў Бэртран дэ Бланфор з чэрапам-святыняй Caput Mortuum.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (16,  16, 'Прысвечана Жаку дэ Мале, апошняму Вялікаму Магістру Ордэну Тампліераў.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (17,  17, 'Арман дэ Лавуа (Арман Перыгорскі) - Вялікі Магістр Ордэну Тампліераў. Даў абет уступіць у Ордэн пасля таго, як ледзь не загінуў пасля падзення ў каня.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (18,  18, 'Роберт дэ Краон быў другім Вялікім Магістрам Ордэну Тампліераў. Ён праявіў сябе як бліскучы арганізатар, чым ператварыў Ордэн у буйную сілу ў дзяржавах крыжакоў.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (19,  19, 'Цібо Гадэн быў Вялікім Магістрам Ордэну і беспаспяхова абараняў крэпасць Сідон. Хугін і Мунін - пара крумкачоў бог Одзіна, што паведамлялі яго пра навіны.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (20,  20, 'Хімічнае вяселле Хрысціяна Разенкрэйца ў 1459 годзе - маніфест Разенкрэйцараў, уяўляе сабой філасофска-сімвалічную прытчу пра семідзённае падарожжа Хрысціяна Разенкрэйца на каралеўскае вяселле.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (21,  21, 'Эвэрар дэ Бар - трэці Вялікі Магістр Ордэна Тампліераў. Па вяртанні са Святой Зямлі адмовіўся ад высокай пасады і сышоў у манастыр.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (22,  22, 'Акко - старажытны горад, што быў заваяваны рыцарамі на чале з Балдуінам І. Да заканчэння Крыжовых Паходаў з''яўляўся сталіцай Іерусалімскага Каралеўства.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (23,  23, 'Крумкач - міфалагічны пасярэднік паміж сусветам жывых і царствам мёртвых, у некаторых эпасах - праклятыя душы.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (24,  24, 'Белы леў - папурны сімвал рыцарскіх ордэнаў сярэднявечча, што сімвалізаваў нябесную моц, дадзеную воіну Хрыстоваму.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (25,  25, 'Губерт Кох - комтур Ордэна, што чакаў прыходу багіні Ісаіс пад гарой Унтэрберг.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (26,  26, 'Жэрар дэ Рыдфар - Вялікі Магістр Ордэна, што прывёў войска Ордэна да суцэльнай паразы ў бітве з арміяй Саладзіна пры Хаціне.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (27,  27, 'Ініцыяваны ў таямніцу дактрыны апелюе да казуістычных аналогіяў, незразумелых для недасведчаных.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (28,  28, 'Вялікі святар-іерафант - тлумач святой таямніцы ў грэкаў і ў заходняй эзатэрыцы. Яго імя нельга ні называць, ні пісаць.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (29,  29, 'Жрыца, што падносіць удзельнікам містэрыі пасудзіны са змесцівам, здольным выклікаць больш светлыя надзеі пра канец жыцця і вечнасць.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (30,  30, 'Ён спяшаецца да моста праз Раку, дзе, прыкрыўшы галаву, каб не пазналі, будзе лаяцца і кпіць з удзельнікаў шэсця, як гэта прадугледжана традыцыяй.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (31,  31, 'Той, хто звычайна суправаджае жадаючых быць пасвечанымі ў таямніцы містэрыі.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (32,  32, 'Той, якому дазволена здымаць пакровы, што ахутваюць галоўную таямніцу.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (33,  33, 'Восьмы дзень містэрыяў, прысвечаны паўтору цырымоніяў дзеля тых, хто прапусціў іх.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (34,  34, 'Тыя, хто бяруць удзел у атлетычных гульнях сёмага дня ў гонар дзвюх багіняў.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (35,  35, 'Уведзеныя ў таямніцу, якія адправіліся ў паломніцтва ў нейкае таемнае месца ў гарах.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (36,  36, 'Майстры, якія валодаюць вялікімі ведамі ў галіне прыроднай магіі, што дазваляюць ім выклікаць звышнатуральныя з''явы.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (37,  37, 'Уведзены ў містэрыю, які прыняў дактрыну таямніцы сваіх сапраўдных поглядаў.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (38,  38, 'Тыя, хто ведае сакрэт гармоніі лічбаў, які іншыя даўно раскрылію.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (39,  39, 'Узведзеныя на другую ступень, рухаюцца ў складзе працэсіі ў бок мора, каб зазнаць нешта асаблівае.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (40,  40, 'Шмат у якіх культурах выяву чарапахі асацыявалі з падмуркам і першапачаткам сусвету.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (41,  41, 'Зграі саранчы, што налічваюць мільярды насякомых утвараюць "лятучыя хмары", пакрываючы і спушташаючы велізарныя плошчы.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (42,  42, 'Карціна прысвечана Ганне Паўлавай - адной з найверлізарных балярынаў ХХ стагоддзя. Скарабей у якасці сімвалу сонца і вяртання.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (43,  43, 'Зразумелая мастацкая метафара на "поп-караля" Майкла Джэксана як чалавека, які змяняў аблічча.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (44,  44, 'Напалеон Банапарт выкарыстоўваў сімвал асы ў якасці эмблемы.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (45,  45, 'Апошняя карціна Вінцэнта ван Гога "Пшанічнае поле з варонамі". Дамаляваўшы палатно, Вінцэнт стрэліў сабе ў грудзі.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (46,  46, '"Мёртвыя галовы" Ёрыка, ружы Ланкастараў і Ёркаў і іх творца Ўільям на метафарычным дэміургу - павуку.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (47,  47, 'Ёган Бах - адзін з найбольш значных кампазітараў сусвету. А птушка калібры вядомая як вястун, які здатны кіраваць часам.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (48,  48, 'Атрутныя джалы скарпіёнаў і пісталет у руцэ бязлітаснага і непахіснага рэвалюцыянера.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (49,  49, 'Пушкін на цвыркуне (сімвале хатняга ачагу) супрацьстаіць мухам як сімвалам зла і моравых эпідэміяў.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (50,  50, 'Верабей сімвалізуе нізасць, бойкасць, прагнасць, пажаднасць.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (51,  51, 'Юры Гагарын стаў першай ластаўкай касмічнай эпохі.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (52,  52, 'Брус Лі ў адной з пазіцыяў кунг-фу, цалкам адпаведнай постаці багамола, гатовага да нападу.', '', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (53,  1, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (54,  2, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (55,  3, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (56,  4, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (57,  5, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (58,  6, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (59,  7, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (60,  8, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (61,  9, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (62,  10, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (63,  11, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (64,  12, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (65,  13, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (66,  14, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (67,  15, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (68,  16, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (69,  17, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (70,  18, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (71,  19, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (72,  20, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (73,  21, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (74,  22, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (75,  23, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (76,  24, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (77,  25, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (78,  26, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (79,  27, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (80,  28, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (81,  29, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (82,  30, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (83,  31, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (84,  32, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (85,  33, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (86,  34, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (87,  35, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (88,  36, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (89,  37, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (90,  38, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (91,  39, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (92,  40, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (93,  41, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (94,  42, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (95,  43, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (96,  44, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (97,  45, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (98,  46, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (99,  47, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (100, 48, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (101, 49, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (102, 50, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (103, 51, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (104, 52, '', '', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (105,  1, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (106,  2, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (107,  3, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (108,  4, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (109,  5, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (110,  6, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (111,  7, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (112,  8, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (113,  9, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (114,  10, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (115,  11, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (116,  12, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (117,  13, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (118,  14, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (119,  15, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (120,  16, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (121,  17, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (122,  18, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (123,  19, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (124,  20, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (125,  21, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (126,  22, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (127,  23, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (128,  24, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (129,  25, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (130,  26, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (131,  27, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (132,  28, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (133,  29, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (134,  30, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (135,  31, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (136,  32, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (137,  33, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (138,  34, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (139,  35, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (140,  36, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (141,  37, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (142,  38, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (143,  39, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (144,  40, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (145,  41, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (146,  42, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (147,  43, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (148,  44, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (149,  45, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (150,  46, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (151,  47, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (152, 48, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (153, 49, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (154, 50, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (155, 51, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (156, 52, '', '', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;
