INSERT INTO magister_cards_images (
      id
    , image_url
    , magister_card_id
    , deck_type_id
    , created_at
    , updated_at
)
VALUES
      (1,  'cards/images/metaphorical/93x133-chirva-tuz.jpeg', 1, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (2,  'cards/images/metaphorical/93x133-chirva-king.jpeg', 2, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (3,  'cards/images/metaphorical/93x133-chirva-dama.jpeg', 3, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (4,  'cards/images/metaphorical/93x133-chirva-valet.jpeg', 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (5,  'cards/images/metaphorical/93x133-chirva-10.jpeg', 5, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (6,  'cards/images/metaphorical/93x133-chirva-9.jpeg', 6, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (7,  'cards/images/metaphorical/93x133-chirva-8.jpeg', 7, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (8,  'cards/images/metaphorical/93x133-chirva-7.jpeg', 8, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (9,  'cards/images/metaphorical/93x133-chirva-6.jpeg', 9, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (10, 'cards/images/metaphorical/93x133-chirva-5.jpeg', 10, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (11, 'cards/images/metaphorical/93x133-chirva-4.jpeg', 11, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (12, 'cards/images/metaphorical/93x133-chirva-3.jpeg', 12, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (13, 'cards/images/metaphorical/93x133-chirva-2.jpeg', 13, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (14, 'cards/images/metaphorical/93x133-tref-tuz.jpeg', 14, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (15, 'cards/images/metaphorical/93x133-tref-king.jpeg', 15, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (16, 'cards/images/metaphorical/93x133-tref-dama.jpeg', 16, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (17, 'cards/images/metaphorical/93x133-tref-valet.jpeg', 17, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (18, 'cards/images/metaphorical/93x133-tref-10.jpeg', 18, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (19, 'cards/images/metaphorical/93x133-tref-9.jpeg', 19, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (20, 'cards/images/metaphorical/93x133-tref-8.jpeg', 20, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (21, 'cards/images/metaphorical/93x133-tref-7.jpeg', 21, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (22, 'cards/images/metaphorical/93x133-tref-6.jpeg', 22, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (23, 'cards/images/metaphorical/93x133-tref-5.jpeg', 23, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (24, 'cards/images/metaphorical/93x133-tref-4.jpeg', 24, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (25, 'cards/images/metaphorical/93x133-tref-3.jpeg', 25, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (26, 'cards/images/metaphorical/93x133-tref-2.jpeg', 26, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (27, 'cards/images/metaphorical/93x133-buba-tuz.jpeg', 27, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (28, 'cards/images/metaphorical/93x133-buba-king.jpeg', 28, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (29, 'cards/images/metaphorical/93x133-buba-dama.jpeg', 29, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (30, 'cards/images/metaphorical/93x133-buba-valet.jpeg', 30, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (31, 'cards/images/metaphorical/93x133-buba-10.jpeg', 31, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (32, 'cards/images/metaphorical/93x133-buba-9.jpeg', 32, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (33, 'cards/images/metaphorical/93x133-buba-8.jpeg', 33, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (34, 'cards/images/metaphorical/93x133-buba-7.jpeg', 34, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (35, 'cards/images/metaphorical/93x133-buba-6.jpeg', 35, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (36, 'cards/images/metaphorical/93x133-buba-5.jpeg', 36, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (37, 'cards/images/metaphorical/93x133-buba-4.jpeg', 37, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (38, 'cards/images/metaphorical/93x133-buba-3.jpeg', 38, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (39, 'cards/images/metaphorical/93x133-buba-2.jpeg', 39, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (40, 'cards/images/metaphorical/93x133-pick-tuz.jpeg', 40, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (41, 'cards/images/metaphorical/93x133-pick-king.jpeg', 41, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (42, 'cards/images/metaphorical/93x133-pick-dama.jpeg', 42, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (43, 'cards/images/metaphorical/93x133-pick-valet.jpeg', 43, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (44, 'cards/images/metaphorical/93x133-pick-10.jpeg', 44, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (45, 'cards/images/metaphorical/93x133-pick-9.jpeg', 45, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (46, 'cards/images/metaphorical/93x133-pick-8.jpeg', 46, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (47, 'cards/images/metaphorical/93x133-pick-7.jpeg', 47, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (48, 'cards/images/metaphorical/93x133-pick-6.jpeg', 48, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (49, 'cards/images/metaphorical/93x133-pick-5.jpeg', 49, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (50, 'cards/images/metaphorical/93x133-pick-4.jpeg', 50, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (51, 'cards/images/metaphorical/93x133-pick-3.jpeg', 51, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (52, 'cards/images/metaphorical/93x133-pick-2.jpeg', 52, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;
