INSERT INTO magister_cards_names (
      id
    , magister_card_id
    , name
    , slug
    , language
    , created_at
    , updated_at
)
VALUES
      (1,   1,  'Zeus and Mnemosyne', 'zeus-and-mnemosyne', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (2,   2,  'Dionysus', 'dionysus', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (3,   3,  'Aphrodite', 'aphrodite', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (4,   4,  'Apollo and Daphne', 'apollo-and-daphne', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (5,   5,  'Persephone', 'persephone', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (6,   6,  'Athena and Erichthonius', 'athena-and-erichthonius', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (7,   7,  'Amphitrite', 'amphitrite', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (8,   8,  'Gaia and Cyclops', 'gaia-and-cyclops', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (9,   9,  'Nymphs of the Water Element', 'nymphs-of-the-water-element', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (10,  10, 'Dryads', 'dryads', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (11,  11, 'Abduction of Europa by Zeus', 'abduction-of-europa-by-zeus', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (12,  12, 'Leda and Swan', 'leda-and-swan', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (13,  13, 'Sirens', 'sirens', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (14,  14, 'Life and Death of the Great Master', 'life-and-death-of-the-great-master', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (15,  15, 'Keeper of Skull', 'keeper-of-skull', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (16,  16, 'Templar''s Hunt', 'templars-hunt', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (17,  17, 'The Miracle about the Horse', 'the-miracle-about-the-horse', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (18,  18, 'Defense of the Castle', 'defense-of-the-castle', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (19,  19, 'Odin''s Raven Munnin near Sidon', 'odins-raven-munnin-near-sidon', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (20,  20, 'Eighth Wedding Day of Christian Rosenkreutz', 'eighth-wedding-day-of-christian-rosenkreutz', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (21,  21, 'Returning of the Shrine', 'returning-of-the-shrine', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (22,  22, 'Celebrations for the Capture of Akko', 'celebrations-for-the-capture-of-akko', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (23,  23, 'Templars Arguing with a Raven', 'templars-arguing-with-a-raven', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (24,  24, 'White Lion Hunting', 'white-lion-hunting', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (25,  25, 'Acquisition of Black Stone near Mount Unterberg', 'acquisition-of-black-stone-near-mount-unterberg', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (26,  26, 'Death in the Battle', 'death-in-the-battle', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (27,  27, 'Carrier of the Light', 'carrier-of-the-light', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (28,  28, 'Priest of the Sacred Temple', 'priest-of-the-sacred-temple', 'EN',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (29,  29, 'Girl with Jugs', 'girl-with-jugs', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (30,  30, 'The Horseman in Helmet', 'the-horseman-in-hemlet', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (31,  31, 'Barrel Bearer', 'barrel-bearer', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (32,  32, 'Secret Initiation Ceremony', 'secret-initiation-ceremony', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (33,  33, 'People Traveling on a Giant''s Hat', 'people-traveling-on-a-giants-hat', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (34,  34, 'Barrels Bearers', 'barrels-bearers', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (35,  35, 'The Holy Chariot', 'the-holy-chariot', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (36,  36, 'Cloud Teamsters', 'cloud-teamsters', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (37,  37, 'Transferring Sacred Objects', 'transfering-sacred-objects', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (38,  38, 'Barrel Carrier', 'barrel-carrier', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (39,  39, 'Two in the Boat', 'two-in-the-boat', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (40,  40, 'Albert Runs at the Turtle''s Speed', 'albert-runs-at-the-turtles-speed', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (41,  41, 'The Secret History of the Mongols', 'the-secret-history-of-the-mongols', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (42,  42, 'Ann and Scrub', 'ann-and-scrub', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (43,  43, 'Michael and the Chameleon', 'michael-and-the-chameleon', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (44,  44, 'The Wasp''s Flight', 'the-wasps-flight', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (45,  45, 'Vincent on the Field', 'vincent-on-the-field', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (46,  46, 'Eighth Sonnet of Shakespeare', 'eighth-sonnet-of-shakespeare', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (47,  47, 'Little Night Serenade', 'little-night-serenade', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (48,  48, 'Che Guevara Surrounded by Scorpions', 'che-guevara-surrounded-by-scorpions', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (49,  49, 'Shot', 'shot', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (50,  50, 'Adolf and Joseph. Aerial Battle', 'adolf-and-joseph-aerial-battle', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (51,  51, 'Ascension of Yuri', 'ascension-of-yuri', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (52,  52, 'Mantis School', 'mantis-school', 'EN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (53,  1,  'Зевс и Мнемозина', 'zevs-i-mnemozina', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (54,  2,  'Дионис', 'dionis', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (55,  3,  'Афродита', 'afrodita', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (56,  4,  'Аполлон и Дафна', 'apollon-i-dafna', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (57,  5,  'Персефона', 'persefona', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (58,  6,  'Афина и Эрихтоний', 'afina-i-erikhtoniy', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (59,  7,  'Амфитрита', 'amfitrita', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (60,  8,  'Гея и циклопы', 'geya-i-tsyklopy', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (61,  9,  'Нимфы водной стихии', 'nimfy-vodnoy-stikhii', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (62,  10, 'Дриады', 'driady', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (63,  11, 'Похищение Европы Зевсом', 'pokhishchenie-evropy-zevsom', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (64,  12, 'Леда и лебедь', 'leda-i-lebed', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (65,  13, 'Сирены', 'sirieny', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (66,  14, 'Жизнь и смерть Великого Магистра', 'zhizn-i-smert-velikogo-magistra', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (67,  15, 'Хранитель черепа', 'khranitel-cherepa', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (68,  16, 'Охота Тамплиера', 'okhota-tampliera', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (69,  17, 'Чудо о коне', 'chudo-o-kone', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (70,  18, 'Защита крепости', 'zashchita-kreposti', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (71,  19, 'Ворон Одина Мунинн возле Сидона', 'voron-odina-muninn-vozle-sidona', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (72,  20, 'Восьмой день свадьбы Христиана Розенкрейца', 'vosmoy-den-svadby-khristiana-rozenkreytsa', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (73,  21, 'Возвращение святыни', 'vozvrashchenie-sviatyni', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (74,  22, 'Торжества в честь взятия Акко', 'torzhestva-v-chest-vziatia-akko', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (75,  23, 'Тамплиеры спорят с вороном', 'tampliery-sporiat-s-voronom', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (76,  24, 'Охота на белого льва', 'okhota-na-belogo-lva', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (77,  25, 'Обретение чёрного камня у горы Унтерберг', 'obretenie-belogo-kamnia-u-gory-unterberg', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (78,  26, 'Смерть в битве', 'smiert-v-bitve', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (79,  27, 'Носитель света', 'nositiel-sveta', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (80,  28, 'Хранитель тайны храма', 'khranitiel-tainy-khrama', 'RU',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (81,  29, 'Девушка с кувшинами', 'dievushka-s-kuvshinami', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (82,  30, 'Всадник в шлеме', 'vsadnik-v-shliemie', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (83,  31, 'Носильщик бочек', 'nosilshchik-bochek', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (84,  32, 'Тайная церемония инициации', 'tainaia-ceremoniia-initsiatsii', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (85,  33, 'Люди путешествуют на шляпе гиганта', 'liudi-puteshestvuiut-na-shliapie-giganta', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (86,  34, 'Носильщики бочек', 'nosilshchiki-bochek', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (87,  35, 'Священная колесница', 'sviashchennaia-kolesnitsa', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (88,  36, 'Погонщики туч', 'pogonshchiki-tuch', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (89,  37, 'Передвижение святынь', 'peredvizheniie-sviatyn', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (90,  38, 'Носильщица бочек', 'nosilshchitsa-bochek', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (91,  39, 'Двое в лодке', 'dvoie-v-lodkie', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (92,  40, 'Альберт бежит со скоростью черепахи', 'albiert-biezhit-so-skorostiiu-chieriepakhi', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (93,  41, 'Тайная история монголов', 'tainaia-istoriia-mongolov', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (94,  42, 'Анна и скарабей', 'anna-i-skarabiey', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (95,  43, 'Майкл и хамелеон', 'maikl-i-khameleon', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (96,  44, 'Полёт осы', 'poliot-osy', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (97,  45, 'Винсент на поле', 'vincent-na-polie', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (98,  46, 'Восьмой сонет Шекспира', 'vosmoy-soniet-shekspira', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (99,  47, 'Маленькая ночная серенада', 'malienkaia-nochnaia-serenada', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (100, 48, 'Че Гевара среди скорпионов', 'che-gevara-sriedi-skorpionov', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (101, 49, 'Выстрел', 'vystrel', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (102, 50, 'Адольф и Иосиф. Воздушный бой', 'adolf-i-iosif-vozdushnyi-boy', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (103, 51, 'Вознесение Юрия', 'vozniesienie-yuriia', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (104, 52, 'Школа богомола', 'shkola-bogomola', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (105,  1, 'Зеўс і Мнемазіна', 'zieus-i-mniemazina', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (106,  2, 'Дыяніс', 'dyianis', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (107,  3, 'Афрадыта', 'afradyta', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (108,  4, 'Апалон і Дафна', 'apalon-i-dafna', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (109,  5, 'Персефона', 'piersefona', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (110,  6, 'Афіна і Эрыхтоній', 'afina-i-erykhtoniy', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (111,  7, 'Амфітрыта', 'amfitryta', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (112,  8, 'Гея і цыклопы', 'gieya-i-cyklopy', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (113,  9, 'Німфы воднай стыхіі', 'nimfy-vodnay-stykhii', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (114, 10, 'Дрыяды', 'dryiady', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (115, 11, 'Выкраданне Еўропы Зеўсам', 'vykradannie-europy-zieusam', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (116, 12, 'Леда і лебедзь', 'leda-i-lebedz', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (117, 13, 'Сірэны', 'sireny', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (118, 14, 'Жыццё і смерць Вялікага Магістра', 'zhyccio-i-smert-vialikaha-magistra', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (119, 15, 'Захавальнік чэрапа', 'zakhavalnik-cherapa', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (120, 16, 'Паляванне Тампліера', 'paliavannie-tampliyera', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (121, 17, 'Цуд пра каня', 'cud-pra-kania', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (122, 18, 'Абарона крэпасці', 'abarona-krepasci', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (123, 19, 'Крумкач Одзіна Мунін каля Сідона', 'krumkach-odzina-munin-kalia-sidona', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (124, 20, 'Восьмы дзень вяселля Хрысціяна Розенкрэйца', 'vosmy-dzien-viasiellia-khrysciyana-rosenkreyca', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (125, 21, 'Вяртанне святыні', 'viartannie-sviatyni', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (126, 22, 'Урачыстасці з нагоды ўзяцця Акко', 'urachystasci-z-nahody-uziaccia-akko', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (127, 23, 'Тампліеры спрачаюцца з крумкачом', 'tampliyery-sprachayucca-z-krumkachom', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (128, 24, 'Паляванне на белага льва', 'paliavannie-na-bielaha-lva', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (129, 25, 'Здабыццё чорнага каменя ля гары Унтэрберг', 'zdabyccio-chornaha-kamienia-lia-hary-unterbierh', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (130, 26, 'Смерць у бітве', 'smierc-u-bitvie', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (131, 27, 'Носьбіт святла', 'nosbit-sviatla', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (132, 28, 'Захавальнік таямніцы храма', 'zakhavalnik-khrama', 'BE',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (133, 29, 'Дзяўчына са збанамі', 'dziauchyna-sa-zbanami', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (134, 30, 'Вершнік у шлеме', 'vershnik-u-shliemie', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (135, 31, 'Носчык бочак', 'noschyk-bochak', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (136, 32, 'Таемная цырымонія ініцыяцыі', 'tayemnaya-cyrymoniya-initsyiacyi', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (137, 33, 'Людзі, што вандруюць на капелюшы гіганта', 'ludzi-shto-vandruyuc-na-kapieliushy-hihanta', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (138, 34, 'Носчыкі бочак', 'noschyki-bochak', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (139, 35, 'Святая калясніца', 'sviataya-kaliasnica', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (140, 36, 'Паганятыя хмараў', 'pahaniatyia-khmarau', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (141, 37, 'Перасоўванне святыняў', 'pierasouvannie-sviatyniau', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (142, 38, 'Носчыца бочак', 'noschyca-bochak', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (143, 39, 'Двое ў чоўне', 'dvoie-u-chounie', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (144, 40, 'Альберт бяжыць з хуткасцю чарапахі', 'albiert-biazhyc-z-khutkasciu-charapakhi', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (145, 41, 'Таемная гісторыя манголаў', 'tayemnaya-historyia-mangolau', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (146, 42, 'Ганна і скарабей', 'hanna-i-skarabiey', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (147, 43, 'Майкл і хамелеон', 'maikl-i-khamielieon', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (148, 44, 'Палёт асы', 'paliot-asy', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (149, 45, 'Вінцэнт на полі', 'vincent-na-poli', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (150, 46, 'Восьмы санет Шэкспіра', 'vosmy-saniet-shekspira', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (151, 47, 'Маленькая начная серэнада', 'malienkaya-nachnaya-serenada', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (152, 48, 'Чэ Гевара сярод скарпіёнаў', 'che-hevara-siarod-skarpiyonau', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (153, 49, 'Стрэл', 'strel', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (154, 50, 'Адольф і Іосіф. Паветраная бойка', 'adolf-i-iosif-pavietranaya-boyka', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (155, 51, 'Узнясенне Юрыя', 'uzniasiennie-yuryia', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    , (156, 52, 'Школа багамола', 'shkola-bagamola', 'BE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;
